server:
  address: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/milk
    data-username: root
    data-password: root
    driver-class-name: com.mysql.jdbc.Driver
  jooq:
    sql-dialect: mysql
