/*
 * This file is generated by jOOQ.
*/
package com.db;


import com.db.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in milk
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>milk.users</code>.
     */
    public static final Users USERS = com.db.tables.Users.USERS;
}
